Don't use jcenter() as a repository
bmuschko/gradle-docker-plugin pull request #989
Opened 2021-02-22 22:05 UTC by orzeh

Fixes #988

2021-02-23 13:38 UTC, cdancy approved these changes
LGTM

2021-02-23 14:05 UTC, bmuschko requested changes

2021-02-23 14:05 UTC, bmuschko commented on src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerListImagesFunctionalTest.groovy
> +                        logger.error("Retuned images: {}", images)
Typo in "returned".

2021-02-23 17:14 UTC, bmuschko commented
Looks like one of the tests is failing though I don't think it's related to your change. Would you mind having a look either way? https://scans.gradle.com/s/iambqfxgdtsto/tests/:functionalTest/com.bmuschko.gradle.docker.tasks.image.DockerListImagesFunctionalTest/can%20list%20images%20with%20image%20name%20filter#1

2021-02-24 09:24 UTC, orzeh commented
@bmuschko yes I've already look into it hence that additional log statement. Unfortunately I have no idea what's wrong - [the output](https://scans.gradle.com/s/lyqzg2oabv6pc/tests/:functionalTest/com.bmuschko.gradle.docker.tasks.image.DockerListImagesFunctionalTest/can%20list%20images%20with%20image%20name%20filter?anchor=e30&focused-exception-line=0-23#1) doesn't make any sense. I think it might be GitHub Actions quirk.

2021-02-24 16:11 UTC, bmuschko commented
@orzeh From what I can see in the output of the test and the logic we have in place there, something seems off.

Output is: `repoTags=[busybox:musl]`
The value we compare it with is: `gradle/16b0d6a166bd426b9c41057dfdc80ac9:latest`

2021-02-26 14:50 UTC, bmuschko commented
@orzeh Could you try to fix the test? We won't be able to merge otherwise. Or we'll have to ignore the test and fix it later but to be honest, we might as well just delete the test then as nobody will look at it.

2021-03-05 18:25 UTC, bmuschko commented
Thanks for the PR. I made the change on `master` as there were additional tests to be fixed.

2021-03-05 18:25 UTC, closed without merging